<<<<<<< HEAD
# Generated by Django 4.2.27 on 2026-01-17 16:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 6.0.1 on 2026-01-16 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
>>>>>>> 87f7c43434723df7253e17f127951eb1ba0ea2ab


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=20, null=True)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('number_of_guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('dietary_restrictions', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='GuestPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledged_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pledged', 'Pledged'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('cancelled', 'Cancelled')], default='pledged', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money (M-Pesa/TigoPesa/AirtelMoney)'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50)),
                ('pledge_date', models.DateField(auto_now_add=True)),
                ('payment_deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pledges', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='weddings.guest')),
=======
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('album_type', models.CharField(choices=[('pre_wedding', 'Pre-Wedding'), ('ceremony', 'Ceremony'), ('reception', 'Reception'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
>>>>>>> 87f7c43434723df7253e17f127951eb1ba0ea2ab
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('photography', 'Photography'), ('videography', 'Videography'), ('flowers', 'Flowers & Decoration'), ('music', 'Music & DJ'), ('transportation', 'Transportation'), ('accommodation', 'Accommodation'), ('invitation', 'Invitation & Stationery'), ('makeup', 'Makeup & Hair'), ('wedding_planner', 'Wedding Planner'), ('other', 'Other')], max_length=50)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('quote', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('negotiating', 'Negotiating'), ('booked', 'Booked'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='inquiry', max_length=20)),
                ('vendor_notes', models.TextField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='vendor_contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor_type', 'status'],
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='GuestPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledged_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pledged', 'Pledged'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('cancelled', 'Cancelled')], default='pledged', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money (M-Pesa/TigoPesa/AirtelMoney)'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50)),
                ('pledge_date', models.DateField(auto_now_add=True)),
                ('payment_deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pledges', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='weddings.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wedding_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='weddings.photogallery')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PledgePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money (M-Pesa/TigoPesa/AirtelMoney)'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction ID, Receipt No, etc', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='weddings.guestpledge')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='weddings.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
>>>>>>> 87f7c43434723df7253e17f127951eb1ba0ea2ab
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=100)),
                ('groom_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-wedding_date'],
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='WeeklyAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('confirmed_count', models.IntegerField()),
                ('pending_count', models.IntegerField()),
                ('spending_to_date', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasks_completed', models.IntegerField()),
                ('tasks_pending', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_snapshots', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Weekly Analytics Snapshots',
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='WeddingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invitations_sent', models.IntegerField(default=0)),
                ('total_confirmed', models.IntegerField(default=0)),
                ('total_pending', models.IntegerField(default=0)),
                ('total_declined', models.IntegerField(default=0)),
                ('average_guests_per_invitation', models.FloatField(default=1.0)),
                ('total_estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_actual_spending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_category_breakdown', models.JSONField(default=dict)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('pending_tasks', models.IntegerField(default=0)),
                ('overdue_tasks', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0)),
                ('total_vendors', models.IntegerField(default=0)),
                ('vendors_booked', models.IntegerField(default=0)),
                ('average_vendor_quote', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vendor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_until_wedding', models.IntegerField(default=0)),
                ('weeks_until_wedding', models.IntegerField(default=0)),
                ('completion_by_milestone', models.JSONField(default=dict)),
                ('planning_health_score', models.FloatField(default=0)),
                ('budget_health_score', models.FloatField(default=0)),
                ('task_health_score', models.FloatField(default=0)),
                ('guest_health_score', models.FloatField(default=0)),
                ('overall_health_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Wedding Analytics',
            },
        ),
        migrations.CreateModel(
            name='VendorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='weddings.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
=======
>>>>>>> 87f7c43434723df7253e17f127951eb1ba0ea2ab
        migrations.AddField(
            model_name='vendor',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='weddings.wedding'),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('save_date', 'Save the Date'), ('invitation', 'Send Invitations'), ('rsvp_deadline', 'RSVP Deadline'), ('final_headcount', 'Final Headcount'), ('ceremony_rehearsal', 'Ceremony Rehearsal'), ('wedding_day', 'Wedding Day'), ('honeymoon', 'Honeymoon'), ('thank_you', 'Send Thank You Cards'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='weddings.wedding')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='weddings.wedding')),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='PledgePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money (M-Pesa/TigoPesa/AirtelMoney)'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction ID, Receipt No, etc', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='weddings.guestpledge')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('album_type', models.CharField(choices=[('pre_wedding', 'Pre-Wedding'), ('ceremony', 'Ceremony'), ('reception', 'Reception'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_albums', to='weddings.wedding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wedding_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='weddings.photogallery')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
=======
        migrations.AddField(
            model_name='photogallery',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_albums', to='weddings.wedding'),
>>>>>>> 87f7c43434723df7253e17f127951eb1ba0ea2ab
        ),
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ceremony_time', models.TimeField(blank=True, null=True)),
                ('ceremony_location', models.CharField(blank=True, max_length=255)),
                ('reception_time', models.TimeField(blank=True, null=True)),
                ('reception_location', models.CharField(blank=True, max_length=255)),
                ('dress_code', models.CharField(blank=True, max_length=100)),
                ('rsvp_deadline', models.DateField(blank=True, null=True)),
                ('rsvp_email', models.EmailField(max_length=254)),
                ('custom_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_template', to='weddings.wedding')),
            ],
        ),
        migrations.AddField(
            model_name='guestpledge',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='weddings.wedding'),
        ),
        migrations.CreateModel(
            name='GuestEngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_response_rate', models.FloatField(default=0)),
                ('average_response_time', models.IntegerField(default=0)),
                ('relationship_breakdown', models.JSONField(default=dict)),
                ('dietary_requirements_percentage', models.FloatField(default=0)),
                ('group_size_distribution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Guest Engagement Metrics',
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='weddings.wedding'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('decoration', 'Decoration'), ('photography', 'Photography'), ('music', 'Music'), ('transportation', 'Transportation'), ('accommodation', 'Accommodation'), ('attire', 'Attire'), ('invitation', 'Invitation'), ('other', 'Other')], max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='weddings.wedding')),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='WeddingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invitations_sent', models.IntegerField(default=0)),
                ('total_confirmed', models.IntegerField(default=0)),
                ('total_pending', models.IntegerField(default=0)),
                ('total_declined', models.IntegerField(default=0)),
                ('average_guests_per_invitation', models.FloatField(default=1.0)),
                ('total_estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_actual_spending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_category_breakdown', models.JSONField(default=dict)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('pending_tasks', models.IntegerField(default=0)),
                ('overdue_tasks', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0)),
                ('total_vendors', models.IntegerField(default=0)),
                ('vendors_booked', models.IntegerField(default=0)),
                ('average_vendor_quote', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vendor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_until_wedding', models.IntegerField(default=0)),
                ('weeks_until_wedding', models.IntegerField(default=0)),
                ('completion_by_milestone', models.JSONField(default=dict)),
                ('planning_health_score', models.FloatField(default=0)),
                ('budget_health_score', models.FloatField(default=0)),
                ('task_health_score', models.FloatField(default=0)),
                ('guest_health_score', models.FloatField(default=0)),
                ('overall_health_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Wedding Analytics',
            },
        ),
        migrations.CreateModel(
            name='WeeklyAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('confirmed_count', models.IntegerField()),
                ('pending_count', models.IntegerField()),
                ('spending_to_date', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasks_completed', models.IntegerField()),
                ('tasks_pending', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_snapshots', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Weekly Analytics Snapshots',
                'ordering': ['week_number'],
            },
        ),
>>>>>>> 87f7c43434723df7253e17f127951eb1ba0ea2ab
    ]
