# Generated by Django 5.2.7 on 2025-10-20 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ceremony_time', models.TimeField(blank=True, null=True)),
                ('ceremony_location', models.CharField(blank=True, max_length=255)),
                ('reception_time', models.TimeField(blank=True, null=True)),
                ('reception_location', models.CharField(blank=True, max_length=255)),
                ('dress_code', models.CharField(blank=True, max_length=100)),
                ('rsvp_deadline', models.DateField(blank=True, null=True)),
                ('rsvp_email', models.EmailField(max_length=254)),
                ('custom_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_template', to='weddings.wedding')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('album_type', models.CharField(choices=[('pre_wedding', 'Pre-Wedding'), ('ceremony', 'Ceremony'), ('reception', 'Reception'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_albums', to='weddings.wedding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wedding_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='weddings.photogallery')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('save_date', 'Save the Date'), ('invitation', 'Send Invitations'), ('rsvp_deadline', 'RSVP Deadline'), ('final_headcount', 'Final Headcount'), ('ceremony_rehearsal', 'Ceremony Rehearsal'), ('wedding_day', 'Wedding Day'), ('honeymoon', 'Honeymoon'), ('thank_you', 'Send Thank You Cards'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='weddings.wedding')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('photography', 'Photography'), ('videography', 'Videography'), ('flowers', 'Flowers & Decoration'), ('music', 'Music & DJ'), ('transportation', 'Transportation'), ('accommodation', 'Accommodation'), ('invitation', 'Invitation & Stationery'), ('makeup', 'Makeup & Hair'), ('wedding_planner', 'Wedding Planner'), ('other', 'Other')], max_length=50)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('quote', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('negotiating', 'Negotiating'), ('booked', 'Booked'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='inquiry', max_length=20)),
                ('vendor_notes', models.TextField(blank=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='vendor_contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='weddings.wedding')),
            ],
            options={
                'ordering': ['vendor_type', 'status'],
            },
        ),
        migrations.CreateModel(
            name='VendorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='weddings.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
