# Generated by Django 5.2.7 on 2025-10-20 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_invitationtemplate_photogallery_photo_timeline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_response_rate', models.FloatField(default=0)),
                ('average_response_time', models.IntegerField(default=0)),
                ('relationship_breakdown', models.JSONField(default=dict)),
                ('dietary_requirements_percentage', models.FloatField(default=0)),
                ('group_size_distribution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Guest Engagement Metrics',
            },
        ),
        migrations.CreateModel(
            name='WeddingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invitations_sent', models.IntegerField(default=0)),
                ('total_confirmed', models.IntegerField(default=0)),
                ('total_pending', models.IntegerField(default=0)),
                ('total_declined', models.IntegerField(default=0)),
                ('average_guests_per_invitation', models.FloatField(default=1.0)),
                ('total_estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_actual_spending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_category_breakdown', models.JSONField(default=dict)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('pending_tasks', models.IntegerField(default=0)),
                ('overdue_tasks', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0)),
                ('total_vendors', models.IntegerField(default=0)),
                ('vendors_booked', models.IntegerField(default=0)),
                ('average_vendor_quote', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vendor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_until_wedding', models.IntegerField(default=0)),
                ('weeks_until_wedding', models.IntegerField(default=0)),
                ('completion_by_milestone', models.JSONField(default=dict)),
                ('planning_health_score', models.FloatField(default=0)),
                ('budget_health_score', models.FloatField(default=0)),
                ('task_health_score', models.FloatField(default=0)),
                ('guest_health_score', models.FloatField(default=0)),
                ('overall_health_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Wedding Analytics',
            },
        ),
        migrations.CreateModel(
            name='WeeklyAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('confirmed_count', models.IntegerField()),
                ('pending_count', models.IntegerField()),
                ('spending_to_date', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasks_completed', models.IntegerField()),
                ('tasks_pending', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_snapshots', to='weddings.wedding')),
            ],
            options={
                'verbose_name_plural': 'Weekly Analytics Snapshots',
                'ordering': ['week_number'],
            },
        ),
    ]
