# Generated by Django 5.2.7 on 2025-12-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0004_guestpledge_pledgepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
