# Generated by Django 5.2.7 on 2025-12-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0005_alter_wedding_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='relationship',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
