# Generated by Django 5.2.7 on 2025-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0006_alter_guest_dietary_restrictions_alter_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
